name: txt2m3u

on:
  push:
    branches: main
  schedule:
    - cron: '30 22 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Request
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: txt2m3u
      run: |
        python txt2m3u.py
      env:
        FILE_PATH: ${{ secrets.FILE_PATH }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_TALK_ID: ${{ secrets.TG_TALK_ID }}

    - name: Remove input
      run: |
        rm -f input.txt

    - name: Push changes
      uses: actions-go/push@master
      with:
        author-email: github-actions@github.com
        author-name: github-actions
        commit-message: 'update m3u data'
        remote: origin
